services:
  ssispro_db:
    image: postgres:latest
    container_name: ssispro_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ssispro_db # ✅ pour créer automatiquement la base
    ports:
      - '5432:5432'
    volumes:
      - ssispro_db:/var/lib/postgresql/data
    networks:
      - ssispro_net

volumes:
  ssispro_db:
    driver: local

networks:
  ssispro_net:
    driver: bridge
