services:
  ssispro_db:
    image: postgres:15
    container_name: ssispro_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ssispro_db # ✅ pour créer automatiquement la base
    ports:
      - '5435:5432'
    volumes:
      - ssispro_db:/var/lib/postgresql/data
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application NextJS
  ssispro_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssispro_app
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@ssispro_db:5432/ssispro_db
      - JWT_SECRET="azertyuiopmlkjhgfdsqqwxcvbn"
      - PORT=3001
      # Ajoutez ici vos autres variables d'environnement
      # - NEXTAUTH_SECRET=your-secret-key
      # - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      ssispro_db:
        condition: service_healthy
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowiseai.rule=Host(`flowise.domain.com`)"
      - "traefik.http.routers.flowiseai.entrypoints=websecure"
      - "traefik.http.routers.flowiseai.tls.certResolver=letsencrypt"
      - "traefik.http.services.flowiseai.loadbalancer.server.port=3000"

volumes:
  ssispro_db:
    driver: local

networks:
  dokploy-network:
    external: true
