version: "3.9"

services:
  # --------------------------
  # Base de données Postgres
  # --------------------------
  ssispro_db:
    image: postgres:15
    container_name: ssispro_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ssispro_db # fixé en dur
    ports:
      - "5435:5432"
    volumes:
      - ssispro_db:/var/lib/postgresql/data
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --------------------------
  # Application NextJS
  # --------------------------
  ssispro_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssispro_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      ssispro_db:
        condition: service_healthy
    networks:
      - dokploy-network

# --------------------------
# Volumes & Réseau
# --------------------------
volumes:
  ssispro_db:
    driver: local

networks:
  dokploy-network:
    external: true
